import { useMemo, useState } from 'react';
import { ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { Link } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { colors, radius, spacing } from '@/theme';

type Profile = 'Conservative' | 'Balanced' | 'Growth';
const money=(v:number)=>`₹${Math.round(Math.max(0,v)).toLocaleString('en-IN')}`;
const n=(v:string,d:number)=>{const x=Number(v.replace(/,/g,''));return Number.isFinite(x)&&x>=0?x:d};
const plans:Record<Profile,{equity:number;debt:number;cash:number;label:string}>= {Conservative:{equity:40,debt:50,cash:10,label:'Capital preservation first'},Balanced:{equity:60,debt:30,cash:10,label:'Growth and stability balanced'},Growth:{equity:80,debt:15,cash:5,label:'Higher growth exposure'}};
export default function InvestmentPlan(){const[amount,setAmount]=useState('100000');const[monthly,setMonthly]=useState('10000');const[profile,setProfile]=useState<Profile>('Balanced');const p=plans[profile];const a=n(amount,100000),m=n(monthly,10000);const rows=useMemo(()=>[{name:'Equity / growth',pct:p.equity,value:a*p.equity/100,monthly:m*p.equity/100},{name:'Debt / stability',pct:p.debt,value:a*p.debt/100,monthly:m*p.debt/100},{name:'Cash / liquidity',pct:p.cash,value:a*p.cash/100,monthly:m*p.cash/100}],[a,m,p]);return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content}><View style={s.top}><Link href="/funds" style={s.back}>‹ Mutual Funds</Link><Text style={s.eyebrow}>INVESTIQ / PLAN</Text></View><Text style={s.title}>Investment Plan</Text><Text style={s.sub}>Turn a portfolio amount and monthly contribution into a transparent allocation starting point.</Text><View style={s.card}><Field label="Portfolio amount" value={amount} onChangeText={setAmount} prefix="₹"/><Field label="Monthly contribution" value={monthly} onChangeText={setMonthly} prefix="₹"/></View><Text style={s.section}>Risk profile</Text><View style={s.profiles}>{(Object.keys(plans) as Profile[]).map(x=><TouchableOpacity key={x} onPress={()=>setProfile(x)} style={[s.profile,profile===x&&s.active]}><Text style={[s.profileText,profile===x&&s.activeText]}>{x}</Text></TouchableOpacity>)}</View><View style={s.hero}><Text style={s.muted}>{profile}</Text><Text style={s.heroTitle}>{p.label}</Text><Text style={s.muted}>Illustrative allocation for discussion and planning only.</Text></View><Text style={s.section}>Allocation</Text><View style={s.card}>{rows.map(r=><View key={r.name} style={s.row}><View style={s.rowLeft}><Text style={s.name}>{r.name}</Text><Text style={s.muted}>{r.pct}% allocation · {money(r.monthly)}/month</Text></View><Text style={s.value}>{money(r.value)}</Text></View>)}</View><View style={s.note}><Text style={s.noteTitle}>Important</Text><Text style={s.noteText}>This is an educational allocation framework, not a personalized recommendation. It does not select securities, execute trades, or guarantee returns. Actual allocation should consider goals, liquidity needs, taxes, risk capacity and suitability.</Text></View></ScrollView></SafeAreaView>}
function Field({label,value,onChangeText,prefix}:{label:string;value:string;onChangeText:(v:string)=>void;prefix?:string}){return <View style={s.field}><Text style={s.label}>{label}</Text><View style={s.inputRow}>{prefix?<Text style={s.affix}>{prefix}</Text>:null}<TextInput value={value} onChangeText={onChangeText} keyboardType="decimal-pad" style={s.input}/></View></View>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:colors.background},content:{padding:spacing.lg,paddingBottom:52,gap:spacing.lg},top:{flexDirection:'row',justifyContent:'space-between'},back:{color:colors.accent,fontSize:13,fontWeight:'700'},eyebrow:{color:colors.muted,fontSize:9,fontWeight:'900',letterSpacing:1.4},title:{color:colors.text,fontSize:31,fontWeight:'900'},sub:{color:colors.muted,fontSize:13,lineHeight:19,marginTop:-8},card:{backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:radius.lg,padding:spacing.lg,gap:14},field:{gap:7},label:{color:colors.muted,fontSize:10,fontWeight:'800'},inputRow:{flexDirection:'row',alignItems:'center',backgroundColor:colors.surfaceElevated,borderWidth:1,borderColor:colors.border,borderRadius:radius.md,paddingHorizontal:12},affix:{color:colors.muted,fontWeight:'800'},input:{flex:1,color:colors.text,fontSize:17,fontWeight:'800',paddingVertical:12,paddingHorizontal:7},section:{color:colors.text,fontSize:19,fontWeight:'900'},profiles:{flexDirection:'row',gap:7},profile:{flex:1,paddingVertical:12,alignItems:'center',borderRadius:radius.md,borderWidth:1,borderColor:colors.border,backgroundColor:colors.surface},active:{backgroundColor:colors.accent,borderColor:colors.accent},profileText:{color:colors.muted,fontSize:10,fontWeight:'900'},activeText:{color:colors.background},hero:{backgroundColor:colors.accentSoft,borderWidth:1,borderColor:colors.border,borderRadius:radius.lg,padding:spacing.lg,gap:5},heroTitle:{color:colors.text,fontSize:20,fontWeight:'900'},muted:{color:colors.muted,fontSize:10,lineHeight:16},row:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',paddingVertical:13,borderBottomWidth:1,borderColor:colors.border},rowLeft:{flex:1,gap:3},name:{color:colors.text,fontSize:12,fontWeight:'900'},value:{color:colors.text,fontSize:14,fontWeight:'900'},note:{backgroundColor:colors.surfaceElevated,borderWidth:1,borderColor:colors.border,borderRadius:radius.md,padding:spacing.md,gap:6},noteTitle:{color:colors.accent,fontSize:9,fontWeight:'900',letterSpacing:1.2},noteText:{color:colors.muted,fontSize:10,lineHeight:16}});