import { useState } from 'react';
import { ActivityIndicator, Alert, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { router } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { getOrCreateDeviceId, saveSession } from '@/auth';
import { colors, radius, spacing } from '@/theme';
import { Platform } from 'react-native';

const API=process.env.EXPO_PUBLIC_API_URL ?? 'http://localhost:3000/api/v1';
export default function LoginScreen(){
 const [username,setUsername]=useState(''); const [password,setPassword]=useState(''); const [challenge,setChallenge]=useState(''); const [code,setCode]=useState(''); const [loading,setLoading]=useState(false);
 async function login(){setLoading(true);try{const deviceId=await getOrCreateDeviceId();const r=await fetch(`${API}/auth/login`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({username,password,device_id:deviceId,device_label:`InvestIQ ${Platform.OS}`})});const data=await r.json();if(!r.ok)throw new Error(data.message??'Login failed');if(data.mfa_required){setChallenge(data.challenge_token);return;}await saveSession(data.access_token,data.refresh_token);router.replace('/profile');}catch(e){Alert.alert('Secure sign-in',e instanceof Error?e.message:'Unable to sign in');}finally{setLoading(false);}}
 async function verify(){setLoading(true);try{const deviceId=await getOrCreateDeviceId();const r=await fetch(`${API}/auth/mfa/verify`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({challenge_token:challenge,code,device_id:deviceId,device_label:`InvestIQ ${Platform.OS}`})});const data=await r.json();if(!r.ok)throw new Error(data.message??'MFA verification failed');await saveSession(data.access_token,data.refresh_token);router.replace('/profile');}catch(e){Alert.alert('MFA verification',e instanceof Error?e.message:'Unable to verify MFA');}finally{setLoading(false);}}
 return <SafeAreaView style={styles.safe}><View style={styles.card}><Text style={styles.eyebrow}>INVESTIQ SECURITY</Text><Text style={styles.title}>{challenge?'Verify your identity':'Sign in securely'}</Text><Text style={styles.sub}>{challenge?'Enter the six-digit code from your authenticator app.':'Your session tokens and device identity are stored only in protected device storage.'}</Text>{!challenge?<><TextInput style={styles.input} autoCapitalize="none" placeholder="Username" placeholderTextColor={colors.muted} value={username} onChangeText={setUsername}/><TextInput style={styles.input} secureTextEntry placeholder="Password" placeholderTextColor={colors.muted} value={password} onChangeText={setPassword}/><Pressable style={styles.button} disabled={loading} onPress={login}>{loading?<ActivityIndicator/>:<Text style={styles.buttonText}>Continue</Text>}</Pressable></>:<><TextInput style={styles.input} keyboardType="number-pad" maxLength={6} placeholder="6-digit MFA code" placeholderTextColor={colors.muted} value={code} onChangeText={setCode}/><Pressable style={styles.button} disabled={loading} onPress={verify}>{loading?<ActivityIndicator/>:<Text style={styles.buttonText}>Verify & enter</Text>}</Pressable></>}<Text style={styles.note}>MFA is enforced server-side. Sensitive operations can require step-up authentication.</Text></View></SafeAreaView>;
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.background,justifyContent:'center',padding:spacing.lg},card:{backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:radius.lg,padding:spacing.lg},eyebrow:{color:colors.accent,fontSize:11,fontWeight:'900',letterSpacing:1.5},title:{color:colors.text,fontSize:28,fontWeight:'900',marginTop:10},sub:{color:colors.muted,fontSize:12,lineHeight:18,marginTop:8},input:{height:52,borderWidth:1,borderColor:colors.border,borderRadius:radius.md,color:colors.text,paddingHorizontal:14,marginTop:14},button:{height:52,borderRadius:radius.md,backgroundColor:colors.accent,alignItems:'center',justifyContent:'center',marginTop:18},buttonText:{color:colors.background,fontWeight:'900'},note:{color:colors.muted,fontSize:10,lineHeight:15,marginTop:18}});
