import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, RefreshControl, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { Link } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { colors, radius, spacing } from '@/theme';

const API_URL = process.env.EXPO_PUBLIC_API_URL ?? 'http://localhost:3000/api/v1';
type Index = { symbol: string; name: string; value: number; change?: number; changePercent?: number; currency?: string; timestamp: string };
type Overview = { available: boolean; marketOpen: boolean | null; indices: Index[]; gainers: unknown[]; losers: unknown[]; active: unknown[]; message?: string };
function value(v:number){return v.toLocaleString('en-IN',{maximumFractionDigits:2});}
function pct(v?:number){return v == null ? '—' : `${v >= 0 ? '+' : ''}${v.toFixed(2)}%`;}
export default function MarketOverviewScreen(){
 const [data,setData]=useState<Overview|null>(null); const [loading,setLoading]=useState(true); const [refreshing,setRefreshing]=useState(false); const [error,setError]=useState<string|null>(null);
 const load=useCallback(async(refresh=false)=>{if(refresh)setRefreshing(true);else setLoading(true);setError(null);try{const r=await fetch(`${API_URL}/market-overview`);const j=await r.json() as Overview;if(!r.ok)throw new Error(j.message??'Market overview unavailable.');setData(j);}catch(e){setError(e instanceof Error?e.message:'Unable to reach the market service.');}finally{setLoading(false);setRefreshing(false);}},[]);
 useEffect(()=>{void load();},[load]);
 return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>void load(true)}/>}> <View style={styles.top}><Link href="/" style={styles.back}>‹ Home</Link><Text style={styles.eyebrow}>MARKET OVERVIEW</Text></View><View><Text style={styles.title}>Indian Market</Text><Text style={styles.subtitle}>Verified index data and market status.</Text></View>
 <View style={styles.status}><View style={styles.statusDot}/><Text style={styles.statusText}>{data?.marketOpen === true ? 'MARKET OPEN' : data?.marketOpen === false ? 'MARKET CLOSED' : 'STATUS UNAVAILABLE'}</Text><Text style={styles.provider}>Verified feed</Text></View>
 {loading?<View style={styles.state}><ActivityIndicator color={colors.accent}/><Text style={styles.muted}>Loading market overview…</Text></View>:error?<View style={styles.card}><Text style={styles.cardTitle}>Market data unavailable</Text><Text style={styles.muted}>{error}</Text><TouchableOpacity onPress={()=>void load()} style={styles.retry}><Text style={styles.retryText}>Retry</Text></TouchableOpacity></View>:<>
 <View style={styles.section}><Text style={styles.sectionTitle}>Major indices</Text>{data?.indices.map(index=><View key={index.symbol} style={styles.index}><View style={styles.indexLeft}><Text style={styles.symbol}>{index.symbol}</Text><Text style={styles.muted}>{index.name}</Text><Text style={styles.time}>{new Date(index.timestamp).toLocaleString()}</Text></View><View style={styles.indexRight}><Text style={styles.value}>{value(index.value)}</Text><Text style={[styles.change,(index.changePercent??0)<0&&styles.negative]}>{pct(index.changePercent)}</Text></View></View>)}</View>
 <View style={styles.card}><Text style={styles.cardTitle}>Gainers & losers</Text><Text style={styles.muted}>{data?.gainers.length || data?.losers.length ? 'Live movers are available from the configured provider.' : 'Verified movers are not exposed by the current market-data provider, so InvestIQ will not invent a ranking.'}</Text></View>
 <View style={styles.card}><Text style={styles.cardTitle}>Market intelligence</Text><Text style={styles.muted}>Use the live news feed for market-moving headlines and open any stock for company-specific news.</Text><Link href="/news" style={styles.link}>Open financial news →</Link></View>
 </>}</ScrollView></SafeAreaView>;
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.background},content:{padding:spacing.lg,paddingBottom:50,gap:spacing.lg},top:{flexDirection:'row',justifyContent:'space-between'},back:{color:colors.accent,fontSize:13,fontWeight:'800'},eyebrow:{color:colors.muted,fontSize:9,fontWeight:'900',letterSpacing:1.3},title:{color:colors.text,fontSize:30,fontWeight:'900'},subtitle:{color:colors.muted,fontSize:12,marginTop:5},status:{flexDirection:'row',alignItems:'center',gap:7,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:radius.md,padding:spacing.md},statusDot:{width:7,height:7,borderRadius:4,backgroundColor:colors.accent},statusText:{color:colors.text,fontSize:10,fontWeight:'900',flex:1},provider:{color:colors.accent,fontSize:8,fontWeight:'900'},section:{backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:radius.lg,padding:spacing.md},sectionTitle:{color:colors.text,fontSize:18,fontWeight:'900',marginBottom:spacing.sm},index:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',paddingVertical:spacing.md,borderTopWidth:1,borderColor:colors.border},indexLeft:{flex:1},symbol:{color:colors.text,fontSize:15,fontWeight:'900'},time:{color:colors.muted,fontSize:8,marginTop:4},indexRight:{alignItems:'flex-end'},value:{color:colors.text,fontSize:20,fontWeight:'900'},change:{color:colors.positive,fontSize:11,fontWeight:'900',marginTop:3},negative:{color:colors.negative},card:{backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:radius.lg,padding:spacing.lg,gap:8},cardTitle:{color:colors.text,fontSize:16,fontWeight:'900'},muted:{color:colors.muted,fontSize:10,lineHeight:16},link:{color:colors.accent,fontSize:11,fontWeight:'900',marginTop:4},retry:{alignSelf:'flex-start',backgroundColor:colors.accent,paddingHorizontal:18,paddingVertical:10,borderRadius:radius.sm},retryText:{color:colors.background,fontSize:10,fontWeight:'900'},state:{padding:spacing.xl,alignItems:'center',gap:12}});