import { useEffect, useState } from 'react';
import { ActivityIndicator, Linking, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { useLocalSearchParams, router } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { colors, radius, spacing } from '@/theme';

const API_URL = process.env.EXPO_PUBLIC_API_URL ?? 'http://localhost:3000/api/v1';
type Article = { id:string; title:string; description?:string; url:string; source:string; publishedAt:string; imageUrl?:string; symbol?:string; category:'market'|'company'|'economy'|'other' };
type NewsResponse = { available:boolean; articles:Article[]; source:string|null; retrievedAt:string; message?:string };

export default function NewsDetailScreen(){
 const params=useLocalSearchParams<{url?:string;title?:string;source?:string;publishedAt?:string;description?:string;symbol?:string;category?:string}>();
 const [article,setArticle]=useState<Article|null>(null); const [loading,setLoading]=useState(true);
 useEffect(()=>{ const url=typeof params.url==='string'?params.url:''; if(!url){setLoading(false);return;} const run=async()=>{try{const q=encodeURIComponent(url);const response=await fetch(`${API_URL}/news?limit=50&q=${q}`);if(!response.ok)return;const data=await response.json() as NewsResponse;const match=data.articles.find(item=>item.url===url);if(match)setArticle(match);}finally{setLoading(false);}};void run();},[params.url]);
 const fallback:Article|undefined=params.url?{id:params.url,title:typeof params.title==='string'?params.title:'Financial news',description:typeof params.description==='string'?params.description:undefined,url:params.url,source:typeof params.source==='string'?params.source:'Verified provider',publishedAt:typeof params.publishedAt==='string'?params.publishedAt:new Date().toISOString(),symbol:typeof params.symbol==='string'?params.symbol:undefined,category:(typeof params.category==='string'&&['market','company','economy','other'].includes(params.category)?params.category:'other') as Article['category']}:undefined;
 const current=article??fallback;
 return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content}>{loading?<View style={styles.center}><ActivityIndicator size="large" color={colors.accent}/><Text style={styles.muted}>Verifying article source…</Text></View>:!current?<View style={styles.card}><Text style={styles.title}>Article unavailable</Text><Text style={styles.muted}>InvestIQ could not verify this article from the configured provider.</Text></View>:<><TouchableOpacity onPress={()=>router.back()}><Text style={styles.back}>‹ Back to news</Text></TouchableOpacity><View style={styles.badge}><Text style={styles.badgeText}>{current.category.toUpperCase()}</Text></View><Text style={styles.title}>{current.title}</Text><Text style={styles.meta}>{current.source} · {new Date(current.publishedAt).toLocaleString()}</Text>{current.symbol?<Text style={styles.symbol}>{current.symbol}</Text>:null}{current.description?<Text style={styles.description}>{current.description}</Text>:null}<View style={styles.card}><Text style={styles.cardTitle}>Source verification</Text><Text style={styles.muted}>Article URL was matched against the configured verified news provider before display.</Text><TouchableOpacity style={styles.button} onPress={()=>void Linking.openURL(current.url)}><Text style={styles.buttonText}>Open original article ›</Text></TouchableOpacity></View><Text style={styles.disclaimer}>InvestIQ displays third-party reporting for information only. The original publisher remains the source of the article and its claims.</Text></>}</ScrollView></SafeAreaView>;
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.background},content:{padding:spacing.lg,paddingBottom:50,gap:spacing.md},center:{paddingVertical:100,alignItems:'center',gap:12},back:{color:colors.accent,fontSize:12,fontWeight:'900'},badge:{alignSelf:'flex-start',backgroundColor:colors.accentSoft,borderRadius:radius.pill,paddingHorizontal:9,paddingVertical:5},badgeText:{color:colors.accent,fontSize:8,fontWeight:'900'},title:{color:colors.text,fontSize:26,fontWeight:'900',lineHeight:34},meta:{color:colors.muted,fontSize:10,lineHeight:16},symbol:{color:colors.accent,fontSize:10,fontWeight:'900'},description:{color:colors.text,fontSize:13,lineHeight:21},card:{backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:radius.lg,padding:spacing.lg,gap:10},cardTitle:{color:colors.text,fontSize:15,fontWeight:'900'},muted:{color:colors.muted,fontSize:10,lineHeight:16},button:{backgroundColor:colors.accent,borderRadius:radius.md,paddingVertical:12,paddingHorizontal:16,alignSelf:'flex-start'},buttonText:{color:colors.background,fontSize:10,fontWeight:'900'},disclaimer:{color:colors.muted,fontSize:9,lineHeight:15}});