import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, RefreshControl, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { getAccessToken } from '@/auth';
import { colors, radius, spacing } from '@/theme';

const API_URL=process.env.EXPO_PUBLIC_API_URL??'http://localhost:3000/api/v1';
type Point={date:string;value:number};
type History={connected?:boolean;history?:Point[];message?:string};
type Analytics={connected?:boolean;source?:string;observations?:number;timeWeightedReturn?:number|null;annualizedReturn?:number|null;maxDrawdown?:number|null;message?:string};
type Risk={available?:boolean;benchmark?:string;observations?:number;alpha?:number|null;beta?:number|null;sharpeRatio?:number|null;riskFreeAnnualized?:number;source?:string;message?:string};
const pct=(v?:number|null)=>v==null?'—':`${(v*100).toFixed(2)}%`;
const num=(v?:number|null)=>v==null?'—':v.toFixed(2);
const money=(v?:number)=>v==null?'—':`₹${Math.round(v).toLocaleString('en-IN')}`;

export default function PortfolioAnalytics(){
 const[data,setData]=useState<Analytics|null>(null); const[risk,setRisk]=useState<Risk|null>(null); const[history,setHistory]=useState<History|null>(null); const[benchmark,setBenchmark]=useState('NIFTY 50'); const[loading,setLoading]=useState(true); const[error,setError]=useState<string|null>(null);
 const load=useCallback(async()=>{setLoading(true);setError(null);try{const token=await getAccessToken();if(!token)throw new Error('Please sign in to view portfolio analytics.');const headers={authorization:`Bearer ${token}`};const symbol=encodeURIComponent(benchmark.trim());const [analyticsResponse,historyResponse,riskResponse]=await Promise.all([fetch(`${API_URL}/trading/portfolio/analytics`,{headers}),fetch(`${API_URL}/trading/portfolio/history`,{headers}),fetch(`${API_URL}/trading/portfolio/risk?symbol=${symbol}`,{headers})]);const analytics=await analyticsResponse.json() as Analytics;const verifiedHistory=await historyResponse.json() as History;const riskData=await riskResponse.json() as Risk;if(!analyticsResponse.ok)throw new Error(analytics.message??'Verified portfolio analytics are unavailable.');if(!historyResponse.ok)throw new Error(verifiedHistory.message??'Verified portfolio history is unavailable.');if(!riskResponse.ok)throw new Error(riskData.message??'Portfolio risk analytics are unavailable.');setData(analytics);setHistory(verifiedHistory);setRisk(riskData)}catch(e){setError(e instanceof Error?e.message:'Verified portfolio analytics are unavailable.')}finally{setLoading(false)}},[benchmark]);
 useEffect(()=>{void load()},[load]);
 const points=history?.history??[]; const first=points[0]?.value; const latest=points.at(-1)?.value;
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content} refreshControl={<RefreshControl refreshing={loading} onRefresh={()=>void load()}/> }>
  <View style={s.top}><Text style={s.eyebrow}>INVESTIQ / ANALYTICS</Text><Text style={s.live}>{data?.connected?'VERIFIED BROKER':'NO BROKER'}</Text></View>
  <Text style={s.title}>Portfolio analytics</Text><Text style={s.subtitle}>Performance and risk metrics returned by the authenticated analytics service from broker-confirmed history.</Text>
  <View style={s.inputCard}><Text style={s.label}>Benchmark for risk analytics</Text><TextInput value={benchmark} onChangeText={setBenchmark} autoCapitalize="characters" autoCorrect={false} placeholder="e.g. NIFTY 50" placeholderTextColor={colors.muted} style={s.input}/><Text style={s.muted}>Use a benchmark symbol supported by verified market history.</Text></View>
  {loading?<View style={s.center}><ActivityIndicator color={colors.accent}/><Text style={s.muted}>Loading verified analytics…</Text></View>:error?<View style={s.card}><Text style={s.heading}>Analytics unavailable</Text><Text style={s.muted}>{error}</Text></View>:<>
   <View style={s.hero}><Text style={s.label}>Latest portfolio value</Text><Text style={s.heroValue}>{money(latest)}</Text><View style={s.grid}><Metric label="Total return" value={pct(data?.timeWeightedReturn)}/><Metric label="Annualized" value={pct(data?.annualizedReturn)}/><Metric label="Max drawdown" value={pct(data?.maxDrawdown)}/></View></View>
   <Text style={s.section}>Risk</Text><View style={s.card}><View style={s.grid}><Metric label="Alpha" value={pct(risk?.alpha)}/><Metric label="Beta" value={num(risk?.beta)}/><Metric label="Sharpe" value={num(risk?.sharpeRatio)}/></View><Text style={s.muted}>{risk?.message??`${risk?.observations??0} verified portfolio/benchmark return pairs used for risk analytics.`}</Text></View>
   <Text style={s.section}>Verified performance</Text><View style={s.card}><Metric label="First observation" value={money(first)}/><Metric label="Latest observation" value={money(latest)}/><Text style={s.muted}>{data?.message??`${data?.observations??points.length} verified observations supplied by the analytics service.`}</Text></View>
  </>}
  <View style={s.note}><Text style={s.noteTitle}>Analytics integrity</Text><Text style={s.muted}>The mobile app does not independently calculate performance or risk metrics. Values come from authenticated server analytics and verified broker/market history. No synthetic prices, returns, alpha, beta or Sharpe values are generated when verified source data is missing.</Text></View>
 </ScrollView></SafeAreaView>;
}
function Metric({label,value}:{label:string;value:string}){return <View style={s.metric}><Text style={s.label}>{label}</Text><Text style={s.value}>{value}</Text></View>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:colors.background},content:{padding:spacing.lg,paddingBottom:55,gap:spacing.lg},top:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},eyebrow:{color:colors.muted,fontSize:9,fontWeight:'900',letterSpacing:1.4},live:{color:colors.accent,fontSize:8,fontWeight:'900'},title:{color:colors.text,fontSize:31,fontWeight:'900'},subtitle:{color:colors.muted,fontSize:12,lineHeight:18,marginTop:-8},center:{alignItems:'center',padding:30,gap:10},inputCard:{backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:radius.lg,padding:spacing.lg,gap:8},input:{backgroundColor:colors.surfaceElevated,borderRadius:radius.md,color:colors.text,fontSize:13,fontWeight:'800',paddingHorizontal:12,paddingVertical:10},hero:{backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:radius.lg,padding:spacing.lg,gap:8},label:{color:colors.muted,fontSize:9,fontWeight:'800'},heroValue:{color:colors.text,fontSize:30,fontWeight:'900'},grid:{flexDirection:'row',gap:9,marginTop:12},metric:{flex:1,backgroundColor:colors.surfaceElevated,borderRadius:radius.md,padding:11,gap:4},value:{color:colors.text,fontSize:13,fontWeight:'900'},section:{color:colors.text,fontSize:19,fontWeight:'900'},card:{backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:radius.lg,padding:spacing.lg,gap:13},heading:{color:colors.text,fontSize:15,fontWeight:'900'},muted:{color:colors.muted,fontSize:10,lineHeight:16},note:{backgroundColor:colors.surfaceElevated,borderRadius:radius.md,padding:spacing.md,gap:5},noteTitle:{color:colors.accent,fontSize:9,fontWeight:'900',letterSpacing:1}});