import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { getAccessToken } from '@/auth';
import { colors, radius, spacing } from '@/theme';
const API_URL=process.env.EXPO_PUBLIC_API_URL??'http://localhost:3000/api/v1';
type Point={date?:string;value?:number};
type Data={connected?:boolean;history?:Point[];message?:string};
const money=(v?:number)=>v==null?'—':`₹${v.toLocaleString('en-IN',{maximumFractionDigits:2})}`;
export default function PortfolioHistory(){const[data,setData]=useState<Data|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);const load=useCallback(async()=>{setLoading(true);setError(null);try{const token=await getAccessToken();if(!token)throw new Error('Please sign in to view portfolio history.');const r=await fetch(`${API_URL}/trading/portfolio/history`,{headers:{authorization:`Bearer ${token}`}});const j=await r.json() as Data;if(!r.ok)throw new Error(j.message??'Portfolio history is unavailable.');setData(j)}catch(e){setError(e instanceof Error?e.message:'Portfolio history is unavailable.')}finally{setLoading(false)}},[]);useEffect(()=>{void load()},[load]);const points=data?.history??[];return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content} refreshControl={<RefreshControl refreshing={loading} onRefresh={()=>void load()}/> }><Text style={s.eyebrow}>INVESTIQ / PORTFOLIO</Text><Text style={s.title}>Portfolio history</Text><Text style={s.subtitle}>Verified account-value history from your connected broker.</Text>{loading?<View style={s.center}><ActivityIndicator color={colors.accent}/><Text style={s.muted}>Loading verified history…</Text></View>:error?<View style={s.card}><Text style={s.heading}>History unavailable</Text><Text style={s.muted}>{error}</Text></View>:points.length<2?<View style={s.card}><Text style={s.heading}>Not enough history yet</Text><Text style={s.muted}>{data?.message??'InvestIQ needs at least two verified historical observations before displaying a performance series.'}</Text></View>:<View style={s.card}><Text style={s.heading}>Verified observations</Text>{points.map((p,i)=><View key={`${p.date??'point'}-${i}`} style={s.row}><Text style={s.muted}>{p.date??'—'}</Text><Text style={s.value}>{money(p.value)}</Text></View>)}</View>}<View style={s.note}><Text style={s.noteTitle}>Integrity first</Text><Text style={s.muted}>No synthetic prices, returns, benchmark values or drawdown series are generated when broker history is missing.</Text></View></ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:colors.background},content:{padding:spacing.lg,paddingBottom:50,gap:spacing.lg},eyebrow:{color:colors.accent,fontSize:9,fontWeight:'900',letterSpacing:1.5},title:{color:colors.text,fontSize:31,fontWeight:'900'},subtitle:{color:colors.muted,fontSize:12,lineHeight:18,marginTop:-8},center:{alignItems:'center',padding:30,gap:10},card:{backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:radius.lg,padding:spacing.lg,gap:12},heading:{color:colors.text,fontSize:15,fontWeight:'900'},row:{flexDirection:'row',justifyContent:'space-between',paddingVertical:11,borderBottomWidth:1,borderBottomColor:colors.border},value:{color:colors.text,fontSize:12,fontWeight:'900'},muted:{color:colors.muted,fontSize:10,lineHeight:16},note:{backgroundColor:colors.surfaceElevated,borderRadius:radius.md,padding:spacing.md,gap:5},noteTitle:{color:colors.accent,fontSize:9,fontWeight:'900',letterSpacing:1}});