import { useMemo } from 'react';
import { ScrollView, StyleSheet, Text, View } from 'react-native';
import { Link } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { colors, radius, spacing } from '@/theme';

type Holding={symbol:string;marketValue:number;unrealizedPnl:number;unrealizedPnlPct:number;sector?:string};
const money=(v:number)=>`₹${Math.round(v).toLocaleString('en-IN')}`;
export default function PortfolioAnalytics(){
 const holdings:Holding[]=[]; const total=useMemo(()=>holdings.reduce((a,x)=>a+x.marketValue,0),[holdings]);
 const sectors=useMemo(()=>Object.entries(holdings.reduce<Record<string,number>>((a,x)=>{const k=x.sector??'Unclassified';a[k]=(a[k]??0)+x.marketValue;return a},{})).sort((a,b)=>b[1]-a[1]),[holdings]);
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content}><View style={s.top}><Link href="/portfolio" style={s.back}>‹ Portfolio</Link><Text style={s.eyebrow}>INVESTIQ / ANALYTICS</Text></View><Text style={s.title}>Portfolio analytics</Text><Text style={s.subtitle}>A verified-data analytics layer for concentration, exposure and performance. Empty states are intentional until broker data is available.</Text><View style={s.hero}><Text style={s.label}>Portfolio value</Text><Text style={s.heroValue}>{total?money(total):'—'}</Text><View style={s.grid}><Metric label="Holdings" value={holdings.length?String(holdings.length):'—'}/><Metric label="Best holding" value="—"/><Metric label="Worst holding" value="—"/></View></View><Text style={s.section}>Performance</Text><View style={s.card}><Metric label="Portfolio return" value="—"/><Metric label="Benchmark return" value="—"/><Metric label="Alpha" value="—"/><Text style={s.muted}>Performance attribution requires broker-confirmed historical portfolio valuations. InvestIQ will not manufacture a return series from today's snapshot.</Text></View><Text style={s.section}>Risk & concentration</Text><View style={s.card}><Metric label="Largest position weight" value="—"/><Metric label="Sector concentration" value="—"/><Metric label="Estimated drawdown" value="—"/><Text style={s.muted}>Risk statistics appear when sufficient verified historical observations are available.</Text></View><Text style={s.section}>Sector exposure</Text><View style={s.card}>{sectors.length?sectors.map(([name,value])=><View key={name} style={s.row}><Text style={s.rowName}>{name}</Text><Text style={s.rowValue}>{total?`${(value/total*100).toFixed(1)}%`:'—'}</Text></View>):<View style={s.empty}><Text style={s.emptyTitle}>No verified sector exposure</Text><Text style={s.muted}>Connect a supported broker and sync positions with sector metadata to populate this analysis.</Text></View>}</View><View style={s.note}><Text style={s.noteTitle}>Analytics integrity</Text><Text style={s.muted}>Portfolio analytics are based only on verified broker or provider data. Missing history, benchmark data or sector classification is shown as unavailable rather than estimated.</Text></View></ScrollView></SafeAreaView>;
}
function Metric({label,value}:{label:string;value:string}){return <View style={s.metric}><Text style={s.label}>{label}</Text><Text style={s.value}>{value}</Text></View>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:colors.background},content:{padding:spacing.lg,paddingBottom:55,gap:spacing.lg},top:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},back:{color:colors.accent,fontSize:13,fontWeight:'800'},eyebrow:{color:colors.muted,fontSize:9,fontWeight:'900',letterSpacing:1.4},title:{color:colors.text,fontSize:31,fontWeight:'900'},subtitle:{color:colors.muted,fontSize:12,lineHeight:18,marginTop:-8},hero:{backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:radius.lg,padding:spacing.lg,gap:8},label:{color:colors.muted,fontSize:9,fontWeight:'800'},heroValue:{color:colors.text,fontSize:30,fontWeight:'900'},grid:{flexDirection:'row',gap:12,marginTop:12},metric:{flex:1,backgroundColor:colors.surfaceElevated,borderRadius:radius.md,padding:12,gap:4},value:{color:colors.text,fontSize:14,fontWeight:'900'},section:{color:colors.text,fontSize:19,fontWeight:'900'},card:{backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:radius.lg,padding:spacing.lg,gap:13},muted:{color:colors.muted,fontSize:10,lineHeight:16},row:{flexDirection:'row',justifyContent:'space-between',paddingVertical:12,borderBottomWidth:1,borderColor:colors.border},rowName:{color:colors.text,fontSize:11,fontWeight:'800'},rowValue:{color:colors.text,fontSize:11,fontWeight:'900'},empty:{paddingVertical:18,gap:6},emptyTitle:{color:colors.text,fontSize:13,fontWeight:'900'},note:{backgroundColor:colors.surfaceElevated,borderRadius:radius.md,padding:spacing.md,gap:5},noteTitle:{color:colors.accent,fontSize:9,fontWeight:'900',letterSpacing:1}});