import { useEffect, useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { router } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { getAccessToken } from '@/auth';
import { colors, radius, spacing } from '@/theme';

const API=process.env.EXPO_PUBLIC_API_URL ?? 'http://localhost:3000/api/v1';
async function authed(path:string,options:RequestInit={}){const token=await getAccessToken();if(!token){router.replace('/login');throw new Error('Sign in required');}const headers={...(options.headers??{}),'content-type':'application/json',authorization:`Bearer ${token}`};const r=await fetch(`${API}${path}`,{...options,headers});const data=await r.json();if(!r.ok)throw new Error(data.message??'Request failed');return data;}
export default function ProfileScreen(){
 const [profile,setProfile]=useState<Record<string,unknown>>({}); const [mfa,setMfa]=useState<{enabled:boolean}>({enabled:false}); const [loading,setLoading]=useState(true); const [setup,setSetup]=useState<{secret:string;otpauth_uri:string}|null>(null); const [code,setCode]=useState(''); const [name,setName]=useState(''); const [city,setCity]=useState(''); const [risk,setRisk]=useState('moderate');
 async function load(){try{const [p,m]=await Promise.all([authed('/profile'),authed('/auth/mfa/status')]);setProfile(p);setMfa(m);setName(typeof p.full_name==='string'?p.full_name:'');setCity(typeof p.city==='string'?p.city:'');setRisk(typeof p.risk_profile==='string'?p.risk_profile:'moderate');}catch(e){Alert.alert('Profile',e instanceof Error?e.message:'Unable to load profile');}finally{setLoading(false);}}
 useEffect(()=>{void load();},[]);
 async function save(){try{await authed('/profile',{method:'PUT',body:JSON.stringify({full_name:name,city,risk_profile:risk})});Alert.alert('Profile','Profile updated securely.');await load();}catch(e){Alert.alert('Profile',e instanceof Error?e.message:'Update failed');}}
 async function startKyc(){try{await authed('/profile/kyc/start',{method:'POST'});Alert.alert('KYC','KYC workflow started. Verification must be completed through an authorized KYC provider.');await load();}catch(e){Alert.alert('KYC',e instanceof Error?e.message:'Unable to start KYC');}}
 async function beginMfa(){try{const result=await authed('/auth/mfa/setup',{method:'POST'});setSetup(result);Alert.alert('MFA setup','Add the provisioning URI to your authenticator app, then enter the generated six-digit code below.');}catch(e){Alert.alert('MFA',e instanceof Error?e.message:'Unable to start MFA');}}
 async function enableMfa(){try{await authed('/auth/mfa/enable',{method:'POST',body:JSON.stringify({code})});setSetup(null);setCode('');await load();Alert.alert('MFA','Multi-factor authentication is now enabled.');}catch(e){Alert.alert('MFA',e instanceof Error?e.message:'Invalid MFA code');}}
 if(loading)return <SafeAreaView style={styles.safe}><Text style={styles.loading}>Loading secure profile…</Text></SafeAreaView>;
 return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content}><View><Text style={styles.eyebrow}>ACCOUNT CENTER</Text><Text style={styles.title}>Your profile</Text><Text style={styles.sub}>Identity, KYC, portfolio preferences and account security.</Text></View>
 <View style={styles.card}><Text style={styles.cardTitle}>Identity profile</Text><TextInput style={styles.input} placeholder="Full legal name" placeholderTextColor={colors.muted} value={name} onChangeText={setName}/><TextInput style={styles.input} placeholder="City" placeholderTextColor={colors.muted} value={city} onChangeText={setCity}/><TextInput style={styles.input} editable={false} value={typeof profile.pan==='string'?profile.pan:''} placeholder="PAN — protected" placeholderTextColor={colors.muted}/><Text style={styles.label}>Risk profile</Text><View style={styles.row}>{['conservative','moderate','aggressive'].map(x=><Pressable key={x} onPress={()=>setRisk(x)} style={[styles.choice,risk===x&&styles.choiceActive]}><Text style={styles.choiceText}>{x}</Text></Pressable>)}</View><Pressable style={styles.button} onPress={save}><Text style={styles.buttonText}>Save profile</Text></Pressable></View>
 <View style={styles.card}><View style={styles.cardHeader}><Text style={styles.cardTitle}>KYC</Text><Text style={styles.badge}>{String(profile.kyc_status??'not_started').replace('_',' ')}</Text></View><Text style={styles.sub}>KYC information is stored with field-level encryption. Final verification must be performed by an authorized securities/KYC intermediary.</Text><Pressable style={styles.secondary} onPress={startKyc}><Text style={styles.secondaryText}>Start KYC verification</Text></Pressable></View>
 <View style={styles.card}><View style={styles.cardHeader}><Text style={styles.cardTitle}>Multi-factor authentication</Text><Text style={styles.badge}>{mfa.enabled?'ENABLED':'NOT ENABLED'}</Text></View>{mfa.enabled?<Text style={styles.sub}>Authenticator-based MFA is active for account sign-in.</Text>:<><Text style={styles.sub}>Protect sign-in with a time-based authenticator code. The server verifies the second factor.</Text><Pressable style={styles.secondary} onPress={beginMfa}><Text style={styles.secondaryText}>Set up authenticator MFA</Text></Pressable>{setup&&<><Text style={styles.secret}>Secret: {setup.secret}</Text><Text style={styles.uri}>{setup.otpauth_uri}</Text><TextInput style={styles.input} keyboardType="number-pad" maxLength={6} placeholder="6-digit code" placeholderTextColor={colors.muted} value={code} onChangeText={setCode}/><Pressable style={styles.button} onPress={enableMfa}><Text style={styles.buttonText}>Enable MFA</Text></Pressable></>}</>}</View>
 <View style={styles.card}><Text style={styles.cardTitle}>Live portfolio connection</Text><Text style={styles.sub}>Your portfolio screen uses verified broker/account data. No synthetic balances, holdings or P&L are generated.</Text><Pressable style={styles.secondary} onPress={()=>router.push('/portfolio')}><Text style={styles.secondaryText}>Open live portfolio</Text></Pressable></View>
 <Text style={styles.disclaimer}>Security design follows OWASP mobile authentication/storage principles. Sensitive profile fields are encrypted at rest; transport must use HTTPS/TLS in production.</Text>
 </ScrollView></SafeAreaView>;
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.background},content:{padding:spacing.lg,paddingBottom:48,gap:spacing.md},loading:{color:colors.text,padding:spacing.lg},eyebrow:{color:colors.accent,fontSize:11,fontWeight:'900',letterSpacing:1.5},title:{color:colors.text,fontSize:30,fontWeight:'900',marginTop:5},sub:{color:colors.muted,fontSize:12,lineHeight:18,marginTop:6},card:{backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:radius.lg,padding:spacing.lg},cardHeader:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},cardTitle:{color:colors.text,fontSize:17,fontWeight:'900'},badge:{color:colors.accent,fontSize:10,fontWeight:'900',textTransform:'uppercase'},input:{height:48,borderWidth:1,borderColor:colors.border,borderRadius:radius.md,color:colors.text,paddingHorizontal:12,marginTop:12},label:{color:colors.muted,fontSize:11,marginTop:14},row:{flexDirection:'row',gap:7,marginTop:8},choice:{flex:1,paddingVertical:10,borderRadius:radius.md,borderWidth:1,borderColor:colors.border,alignItems:'center'},choiceActive:{backgroundColor:colors.accentSoft,borderColor:colors.accent},choiceText:{color:colors.text,fontSize:10,fontWeight:'800',textTransform:'capitalize'},button:{height:48,borderRadius:radius.md,backgroundColor:colors.accent,alignItems:'center',justifyContent:'center',marginTop:14},buttonText:{color:colors.background,fontWeight:'900'},secondary:{height:48,borderRadius:radius.md,borderWidth:1,borderColor:colors.accent,alignItems:'center',justifyContent:'center',marginTop:14},secondaryText:{color:colors.accent,fontWeight:'900'},secret:{color:colors.text,fontSize:11,lineHeight:17,marginTop:12},uri:{color:colors.muted,fontSize:9,lineHeight:14,marginTop:7},disclaimer:{color:colors.muted,fontSize:10,lineHeight:15,paddingVertical:8}});
