import { useEffect, useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { getAccessToken } from '@/auth';
import { biometricAvailability, isBiometricLockEnabled, setBiometricLockEnabled } from '@/biometrics';
import { colors, radius, spacing } from '@/theme';

const API=process.env.EXPO_PUBLIC_API_URL ?? 'http://localhost:3000/api/v1';
async function authed(path:string, options:RequestInit={}) { const token=await getAccessToken(); if(!token){router.replace('/login');throw new Error('Sign in required');} const r=await fetch(`${API}${path}`,{...options,headers:{...(options.headers??{}),authorization:`Bearer ${token}`,'content-type':'application/json'}}); const data=await r.json(); if(!r.ok)throw new Error(data.message??'Request failed'); return data; }

export default function SecurityScreen(){
 const [biometric,setBiometric]=useState(false); const [sessions,setSessions]=useState<Array<Record<string,unknown>>>([]); const [loading,setLoading]=useState(true);
 async function load(){try{const [enabled,list]=await Promise.all([isBiometricLockEnabled(),authed('/auth/sessions')]);setBiometric(enabled);setSessions(Array.isArray(list)?list:[]);}catch(e){Alert.alert('Security',e instanceof Error?e.message:'Unable to load security settings');}finally{setLoading(false);}}
 useEffect(()=>{void load();},[]);
 async function toggle(){try{const next=await setBiometricLockEnabled(!biometric);setBiometric(next);Alert.alert('Security',next?'Biometric app lock enabled.':'Biometric app lock disabled.');}catch(e){Alert.alert('Biometric security',e instanceof Error?e.message:'Unable to change biometric protection');}}
 async function revoke(id:string){try{await authed(`/auth/sessions/${encodeURIComponent(id)}/revoke`,{method:'POST'});await load();}catch(e){Alert.alert('Session',e instanceof Error?e.message:'Unable to revoke session');}}
 async function revokeOthers(){try{await authed('/auth/sessions/revoke-others',{method:'POST'});await load();}catch(e){Alert.alert('Sessions',e instanceof Error?e.message:'Unable to revoke sessions');}}
 if(loading)return <SafeAreaView style={styles.safe}><Text style={styles.loading}>Loading security center…</Text></SafeAreaView>;
 return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content}><Text style={styles.eyebrow}>SECURITY CENTER</Text><Text style={styles.title}>Protect your account</Text><Text style={styles.sub}>Security controls are enforced by the API; this screen never acts as the final authorization boundary.</Text>
 <View style={styles.card}><Text style={styles.cardTitle}>Biometric app lock</Text><Text style={styles.sub}>Use Face ID, Touch ID or an enrolled Android biometric to unlock InvestIQ on this device. This is a local device gate; financial authorization remains server-side.</Text><Text style={styles.status}>{biometric?'ENABLED':'DISABLED'}</Text><Pressable style={styles.button} onPress={toggle}><Text style={styles.buttonText}>{biometric?'Disable biometric lock':'Enable biometric lock'}</Text></Pressable></View>
 <View style={styles.card}><Text style={styles.cardTitle}>Trusted sessions</Text><Text style={styles.sub}>Only sessions belonging to your account are shown. Device identifiers are not exposed.</Text>{sessions.map((s)=><View key={String(s.id)} style={styles.session}><View style={styles.sessionMain}><Text style={styles.sessionTitle}>{String(s.deviceLabel??'Unlabelled device')}</Text><Text style={styles.sessionMeta}>{String(s.ipAddress??'IP unavailable')} · last used {String(s.lastUsedAt??'unknown')}</Text></View><Pressable onPress={()=>revoke(String(s.id))}><Text style={styles.revoke}>Revoke</Text></Pressable></View>)}<Pressable style={styles.secondary} onPress={revokeOthers}><Text style={styles.secondaryText}>Log out other devices</Text></Pressable></View>
 <Pressable style={styles.back} onPress={()=>router.back()}><Text style={styles.backText}>Back to profile</Text></Pressable>
 </ScrollView></SafeAreaView>;
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.background},content:{padding:spacing.lg,paddingBottom:48,gap:spacing.md},loading:{color:colors.text,padding:spacing.lg},eyebrow:{color:colors.accent,fontSize:11,fontWeight:'900',letterSpacing:1.5},title:{color:colors.text,fontSize:30,fontWeight:'900',marginTop:5},sub:{color:colors.muted,fontSize:12,lineHeight:18,marginTop:6},card:{backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:radius.lg,padding:spacing.lg},cardTitle:{color:colors.text,fontSize:17,fontWeight:'900'},status:{color:colors.accent,fontSize:10,fontWeight:'900',marginTop:14},button:{height:48,borderRadius:radius.md,backgroundColor:colors.accent,alignItems:'center',justifyContent:'center',marginTop:14},buttonText:{color:colors.background,fontWeight:'900'},secondary:{height:48,borderRadius:radius.md,borderWidth:1,borderColor:colors.accent,alignItems:'center',justifyContent:'center',marginTop:14},secondaryText:{color:colors.accent,fontWeight:'900'},session:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',paddingVertical:14,borderBottomWidth:1,borderBottomColor:colors.border},sessionMain:{flex:1,paddingRight:10},sessionTitle:{color:colors.text,fontWeight:'800'},sessionMeta:{color:colors.muted,fontSize:10,marginTop:4},revoke:{color:colors.accent,fontSize:11,fontWeight:'900'},back:{alignItems:'center',padding:12},backText:{color:colors.muted,fontWeight:'800'}});
