import { BadRequestException, Body, Controller, Get, Headers, Param, Post, Query, Req, Sse, UseGuards } from '@nestjs/common';
import type { Observable } from 'rxjs';
import type { OrderRequest } from '@investiq/domain';
import { AuthGuard } from './auth.guard';
import type { AuthenticatedRequest } from './auth.types';
import { PermissionGuard } from './permission.guard';
import { TradingEventsService, type TradingSseMessage } from './trading-events.service';
import { TradingService } from './trading.service';
import { TradingReconciliationService } from './trading-reconciliation.service';
import { TransactionAuthorizationService } from './transaction-authorization.service';
import { PortfolioHistoryService } from './portfolio-history.service';
import { PortfolioAnalyticsService } from './portfolio-analytics.service';
import { MarketDataService } from './market-data.service';

interface TransactionVerificationBody { otp?: unknown; }
function otp(value: unknown): string { if (typeof value !== 'string' || !/^\d{6}$/.test(value)) throw new BadRequestException('otp must be a 6-digit code'); return value; }

@Controller('trading')
export class TradingController {
  constructor(private readonly trading: TradingService, private readonly reconciliation: TradingReconciliationService, private readonly events: TradingEventsService, private readonly transactionAuthorization: TransactionAuthorizationService, private readonly portfolioHistoryService: PortfolioHistoryService, private readonly analytics: PortfolioAnalyticsService, private readonly marketData: MarketDataService) {}
  @Get('status') status() { return this.trading.status(); }
  @Get('capabilities') capabilities() { return this.trading.capabilities(); }
  @Get('quote') quote(@Query('symbol') symbol?: string) { if (!symbol?.trim()) throw new BadRequestException('symbol query parameter is required'); return this.trading.quote(symbol); }
  @UseGuards(AuthGuard, PermissionGuard('orders:create')) @Post('orders/preview') preview(@Req() req: AuthenticatedRequest, @Body() request: OrderRequest) { return this.trading.preview(req.user!.id, request); }
  @UseGuards(AuthGuard, PermissionGuard('orders:create')) @Post('transaction-authorizations') createTransactionAuthorization(@Req() req: AuthenticatedRequest, @Body() request: OrderRequest) { return this.transactionAuthorization.createChallenge(req.user!.id, request); }
  @UseGuards(AuthGuard, PermissionGuard('orders:create')) @Post('transaction-authorizations/:id/verify') verifyTransactionAuthorization(@Req() req: AuthenticatedRequest, @Param('id') id: string, @Body() body: TransactionVerificationBody) { return this.transactionAuthorization.verifyChallenge(req.user!.id, id, otp(body.otp)); }
  @UseGuards(AuthGuard, PermissionGuard('orders:create')) @Post('orders') placeOrder(@Req() req: AuthenticatedRequest, @Body() request: OrderRequest, @Headers('idempotency-key') key?: string, @Headers('x-transaction-authorization') transactionAuthorization?: string) { return this.trading.placeOrder(req.user!.id, request, key, transactionAuthorization); }
  @UseGuards(AuthGuard, PermissionGuard('orders:read')) @Get('orders') listOrders(@Req() req: AuthenticatedRequest) { return this.trading.listOrders(req.user!.id); }
  @UseGuards(AuthGuard, PermissionGuard('orders:read')) @Get('orders/:id') getOrder(@Req() req: AuthenticatedRequest, @Param('id') id: string) { return this.trading.getOrder(req.user!.id, id); }
  @UseGuards(AuthGuard, PermissionGuard('orders:cancel')) @Post('orders/:id/cancel') cancelOrder(@Req() req: AuthenticatedRequest, @Param('id') id: string) { return this.trading.cancelOrder(req.user!.id, id); }
  @UseGuards(AuthGuard, PermissionGuard('portfolio:read')) @Get('positions') positions(@Req() req: AuthenticatedRequest) { return this.trading.positions(req.user!.id); }
  @UseGuards(AuthGuard, PermissionGuard('portfolio:read')) @Get('portfolio/history') portfolioHistory(@Req() req: AuthenticatedRequest, @Query('days') days?: string) { return this.portfolioHistoryService.get(req.user!.id, Number(days ?? 365)); }
  @UseGuards(AuthGuard, PermissionGuard('portfolio:read')) @Get('portfolio/analytics') async portfolioAnalytics(@Req() req: AuthenticatedRequest, @Query('days') days?: string) { const history=await this.portfolioHistoryService.get(req.user!.id,Number(days??365)); const observations=history.history.map((p)=>({date:p.date,value:p.value})); return {connected:history.connected,source:history.source??'verified-broker-account-equity',observations:observations.length,timeWeightedReturn:this.analytics.timeWeightedReturn(observations),annualizedReturn:this.analytics.annualizedReturn(observations),maxDrawdown:this.analytics.maxDrawdown(observations),message:observations.length<2?'At least two verified portfolio observations are required for performance analytics.':undefined}; }
  @UseGuards(AuthGuard, PermissionGuard('portfolio:read')) @Get('portfolio/benchmark') async portfolioBenchmark(@Req() req: AuthenticatedRequest,@Query('symbol') symbol?:string,@Query('days') days?:string){const benchmarkSymbol=symbol?.trim();if(!benchmarkSymbol)throw new BadRequestException('symbol query parameter is required');if(benchmarkSymbol.length>40)throw new BadRequestException('symbol must be between 1 and 40 characters');const history=await this.portfolioHistoryService.get(req.user!.id,Number(days??365));const observations=history.history.map((p)=>({date:p.date,value:p.value}));if(observations.length<2)return{connected:history.connected,benchmark:benchmarkSymbol,available:false,benchmarkReturn:null,relativeReturn:null,message:'At least two verified portfolio observations are required for benchmark comparison.'};const benchmark=await this.marketData.history(benchmarkSymbol,observations[0].date,observations[observations.length-1].date);const benchmarkObservations=benchmark.points.map((p)=>({date:p.timestamp,value:p.close}));const benchmarkReturn=this.analytics.benchmarkReturn(benchmarkObservations);const relativeReturn=this.analytics.relativeReturn(observations,benchmarkObservations);return{connected:history.connected,benchmark:benchmarkSymbol,available:benchmark.available&&benchmarkReturn!=null,source:benchmark.source,observations:benchmarkObservations.length,benchmarkReturn,portfolioReturn:this.analytics.timeWeightedReturn(observations),relativeReturn,message:benchmarkReturn==null?(benchmark.message??'Verified benchmark history is insufficient for comparison.'):undefined};}
  @UseGuards(AuthGuard, PermissionGuard('portfolio:read')) @Get('portfolio/risk') async portfolioRisk(@Req() req: AuthenticatedRequest,@Query('symbol') symbol?:string,@Query('days') days?:string,@Query('riskFreeAnnualized') riskFree?:string){const benchmarkSymbol=symbol?.trim();if(!benchmarkSymbol)throw new BadRequestException('symbol query parameter is required');const riskFreeAnnualized=riskFree==null?0:Number(riskFree);if(!Number.isFinite(riskFreeAnnualized)||riskFreeAnnualized<-1||riskFreeAnnualized>1)throw new BadRequestException('riskFreeAnnualized must be between -1 and 1');const history=await this.portfolioHistoryService.get(req.user!.id,Number(days??365));const portfolio=history.history.map((p)=>({date:p.date,value:p.value}));if(portfolio.length<2)return{available:false,beta:null,alpha:null,sharpeRatio:null,message:'At least two verified portfolio observations are required for risk analytics.'};const benchmark=await this.marketData.history(benchmarkSymbol,portfolio[0].date,portfolio[portfolio.length-1].date);const benchmarkObs=benchmark.points.map((p)=>({date:p.timestamp,value:p.close}));const beta=this.analytics.beta(portfolio,benchmarkObs);const alpha=this.analytics.alpha(portfolio,benchmarkObs,riskFreeAnnualized);const sharpeRatio=this.analytics.sharpeRatio(portfolio,riskFreeAnnualized);return{connected:history.connected,benchmark:benchmarkSymbol,available:benchmark.available&&beta!=null&&alpha!=null&&sharpeRatio!=null,observations:this.analytics.pairedReturns(portfolio,benchmarkObs).length,beta,alpha,sharpeRatio,riskFreeAnnualized,source:benchmark.source,message:beta==null||alpha==null||sharpeRatio==null?(benchmark.message??'Verified aligned observations are insufficient for risk analytics.'):undefined};}
  @UseGuards(AuthGuard, PermissionGuard('portfolio:read')) @Get('portfolio/concentration') async portfolioConcentration(@Req() req: AuthenticatedRequest) { const positions=await this.trading.positions(req.user!.id); return { available: positions.length>0, ...this.analytics.concentration(positions.map((position)=>({symbol:position.symbol,marketValue:position.marketValue}))), message:positions.length===0?'No verified portfolio positions are available for concentration analytics.':undefined }; }
  @UseGuards(AuthGuard, PermissionGuard('portfolio:read')) @Get('portfolio/holdings/performance') async portfolioHoldingsPerformance(@Req() req: AuthenticatedRequest) { const positions=await this.trading.positions(req.user!.id); const result=this.analytics.bestWorstHoldings(positions.map((position)=>({symbol:position.symbol,marketValue:position.marketValue,unrealizedPnl:position.unrealizedPnl,unrealizedPnlPct:position.unrealizedPnlPct}))); return { available: result!=null, ...result, message:result==null?'No verified holding P&L data is available for best/worst holding analytics.':undefined }; }
  @UseGuards(AuthGuard, PermissionGuard('account:read')) @Get('account') account(@Req() req: AuthenticatedRequest) { return this.trading.account(req.user!.id); }
  @UseGuards(AuthGuard, PermissionGuard('account:read')) @Get('reconciliation') reconcile(@Req() req: AuthenticatedRequest) { return this.reconciliation.reconcile(req.user!.id); }
  @UseGuards(AuthGuard, PermissionGuard('orders:read')) @Get('events') listEvents(@Req() req: AuthenticatedRequest,@Query('afterId') afterId?:string,@Query('limit') limit?:string){return this.events.list(req.user!.id,Number(afterId??0),Number(limit??100));}
  @UseGuards(AuthGuard, PermissionGuard('orders:read')) @Sse('events/stream') eventStream(@Req() req: AuthenticatedRequest,@Query('afterId') afterId?:string):Observable<TradingSseMessage>{return this.events.stream(req.user!.id,Number(afterId??0));}
}